language: elixir
sudo: false
elixir:
  - 1.8
  - 1.9
  - '1.10'
otp_release:
  - 21.2
  - 22.3
  - 23.0
env:
  - MIX_ENV=test
script:
  - mix test
cache:
  directories:
    - ~/.mix
    - ~/.hex
    - deps
    - _build
jobs:
  exclude:
    - elixir: 1.8
      otp_release: 23.0
    - elixir: 1.9
      otp_release: 23.0
  include:
    - stage: format
      env:
        - MIX_ENV=dev
      script: mix format --check-formatted
      elixir: 1.8
    - stage: dialyzer
      env:
        - MIX_ENV=dev
      before_script: travis_wait mix dialyzer --plt
      script: mix dialyzer --halt-exit-status
      elixir: 1.8
