name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Build and test

    strategy:
      matrix:
        elixir: ['1.8', '1.9', '1.10']
        otp: ['21.2', '22.3', '23.0']
        exclude:
            - elixir: '1.8'
              otp: '23.0'
            - elixir: '1.9'
              otp: '23.0'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
